const navButtons=[...document.querySelectorAll('.side-nav button')];
const views=[...document.querySelectorAll('.view')];
const toast=document.getElementById('toast');
let fixed=false;
function showToast(msg){toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}
navButtons.forEach(btn=>btn.addEventListener('click',()=>{navButtons.forEach(b=>b.classList.remove('active'));btn.classList.add('active');views.forEach(v=>v.classList.remove('active'));document.getElementById('view-'+btn.dataset.view).classList.add('active')}));
document.querySelectorAll('[data-action="inspect"]').forEach(b=>b.addEventListener('click',()=>showToast('Prototype: this would jump to the affected Solid Edge file.')));
document.getElementById('rescanBtn').addEventListener('click',()=>{showToast('Preflight completed · 398 rules evaluated');document.getElementById('lastRun').textContent='Last scan · just now'});
function applyFixedState(){fixed=true;document.getElementById('bigScore').innerHTML='100<span>%</span>';document.getElementById('meterFill').style.width='100%';document.getElementById('readinessText').textContent='All blocking release checks passed.';document.getElementById('blockingCount').textContent='0';document.getElementById('warningCount').textContent='0';document.querySelectorAll('.qa-row').forEach(row=>{row.dataset.state='ok';const icon=row.querySelector('.status-icon');icon.className='status-icon ok';icon.textContent='✓';if(row.dataset.type==='drawing')row.querySelector('strong').textContent='73 / 73';if(row.dataset.type==='flat')row.querySelector('strong').textContent='42 / 42';if(row.dataset.type==='revision')row.querySelector('strong').textContent='186 / 186'});document.getElementById('issuesList').innerHTML='<div style="padding:38px;text-align:center;color:#718096"><b style="display:block;color:#1f9d68;margin-bottom:6px">✓ No open release issues</b>All blocking checks and warnings have been resolved in this simulated project.</div>';document.getElementById('releaseBtn').disabled=false;const big=document.getElementById('releaseBigBtn');big.disabled=false;big.textContent='Generate manufacturing release';showToast('Simulation complete · project is release-ready')}
document.getElementById('fixAllBtn').addEventListener('click',applyFixedState);
function generateRelease(){if(!fixed)return;showToast('Release pack generated · MACHINE_2547_REV_C');}
document.getElementById('releaseBtn').addEventListener('click',generateRelease);document.getElementById('releaseBigBtn').addEventListener('click',generateRelease);
